version: 2

models:
  - name: int_gt__overall_trends
  - name: int_gt__related_trends
  - name: int_hn__stories_engagement
  - name: int_hn__stories_outliers
  - name: int_hn__top_level_comments
    config:
      materialized: table
  - name: int_hn__entity_text_kw_search
    config:
      materialized: table

