sources:
  - name: raw_data
    database: analytics
    tables:
      - name: stories
      - name: comments
      - name: entity_text
      - name: gt_overall_trends
      - name: gt_related_trends
      - name: trending_related_terms